//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u24637646_HW03.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customers()
        {
            this.orders = new HashSet<orders>();
        }

        [DisplayName("Customer ID")]
        public int customer_id { get; set; }

        [DisplayName("First Name")]
        public string first_name { get; set; }

        [DisplayName("Last Name")]
        public string last_name { get; set; }

        [DisplayName("Phone Number")]
        public string phone { get; set; }

        [DisplayName("Email Address")]
        public string email { get; set; }

        [DisplayName("Street")]
        public string street { get; set; }

        [DisplayName("City")]
        public string city { get; set; }

        [DisplayName("State")]
        public string state { get; set; }

        [DisplayName("Zip Code")]
        public string zip_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
